//
// Marshalling code for Open Wire Format for BrokerInfo
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;
using System.IO;

using OpenWire.Core;
using OpenWire.Core.Commands;
using OpenWire.Core.IO;

namespace OpenWire.Core.IO
{
    public class BrokerInfoMarshaller : AbstractCommandMarshaller
    {

        public override Command CreateCommand() {
            return new BrokerInfo();
        }

        public override void BuildCommand(Command command, BinaryReader dataIn) {
            super.buildCommand(command, dataIn);
            BrokerInfo info = (BrokerInfo) command;
            info.setBrokerId((org.apache.activemq.command.BrokerId) readObject(dataIn));
            info.setBrokerURL(dataIn.readUTF());
            info.setPeerBrokerInfos((org.apache.activemq.command.BrokerInfo[]) readObject(dataIn));
            info.setBrokerName(dataIn.readUTF());

        }

        public override void WriteCommand(Command command, BinaryWriter dataOut) {
            super.writeCommand(command, dataOut);
            BrokerInfo info = (BrokerInfo) command;
            writeObject(info.getBrokerId(), dataOut);
            writeUTF(info.getBrokerURL(), dataOut);
            writeObject(info.getPeerBrokerInfos(), dataOut);
            writeUTF(info.getBrokerName(), dataOut);

        }
    }
}
