//
// Marshalling code for Open Wire Format for DataResponse
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;
using System.IO;

using OpenWire.Core;
using OpenWire.Core.Commands;
using OpenWire.Core.IO;

namespace OpenWire.Core.IO
{
    public class DataResponseMarshaller : AbstractCommandMarshaller
    {


        public override Command CreateCommand() {
            return new DataResponse();
        }

        public override void BuildCommand(Command command, BinaryReader dataIn) {
            base.BuildCommand(command, dataIn);

            DataResponse info = (DataResponse) command;
            info.Data = ReadDataStructure(dataIn);

        }

        public override void WriteCommand(Command command, BinaryWriter dataOut) {
            base.WriteCommand(command, dataOut);

            DataResponse info = (DataResponse) command;
            WriteDataStructure(info.Data, dataOut);

        }
    }
}
