//
// Marshalling code for Open Wire Format for ExceptionResponse
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;
using System.IO;

using OpenWire.Core;
using OpenWire.Core.Commands;
using OpenWire.Core.IO;

namespace OpenWire.Core.IO
{
    public class ExceptionResponseMarshaller : AbstractCommandMarshaller
    {


        public override Command CreateCommand() {
            return new ExceptionResponse();
        }

        public override void BuildCommand(Command command, BinaryReader dataIn) {
            base.BuildCommand(command, dataIn);

            ExceptionResponse info = (ExceptionResponse) command;
            info.Exception = ReadThrowable(dataIn);

        }

        public override void WriteCommand(Command command, BinaryWriter dataOut) {
            base.WriteCommand(command, dataOut);

            ExceptionResponse info = (ExceptionResponse) command;
            WriteThrowable(info.Exception, dataOut);

        }
    }
}
