//
// Marshalling code for Open Wire Format for JournalQueueAck
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;
using System.IO;

using OpenWire.Core;
using OpenWire.Core.Commands;
using OpenWire.Core.IO;

namespace OpenWire.Core.IO
{
    public class JournalQueueAckMarshaller : AbstractCommandMarshaller
    {


        public override Command CreateCommand() {
            return new JournalQueueAck();
        }

        public override void BuildCommand(Command command, BinaryReader dataIn) {
            base.BuildCommand(command, dataIn);

            JournalQueueAck info = (JournalQueueAck) command;
            info.Destination = ReadDestination(dataIn);
            info.MessageAck = ReadMessageAck(dataIn);

        }

        public override void WriteCommand(Command command, BinaryWriter dataOut) {
            base.WriteCommand(command, dataOut);

            JournalQueueAck info = (JournalQueueAck) command;
            WriteDestination(info.Destination, dataOut);
            WriteMessageAck(info.MessageAck, dataOut);

        }
    }
}
