//
// Marshalling code for Open Wire Format for MessageId
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;
using System.IO;

using OpenWire.Core;
using OpenWire.Core.Commands;
using OpenWire.Core.IO;

namespace OpenWire.Core.IO
{
    public class MessageIdMarshaller : AbstractCommandMarshaller
    {

        public override Command CreateCommand() {
            return new MessageId();
        }

        public override void BuildCommand(Command command, BinaryReader dataIn) {
            base.BuildCommand(command, dataIn);
            MessageId info = (MessageId) command;
            info.setProducerId((org.apache.activemq.command.ProducerId) readObject(dataIn));
            info.setProducerSequenceId(dataIn.readLong());
            info.setBrokerSequenceId(dataIn.readLong());

        }

        public override void WriteCommand(Command command, BinaryWriter dataOut) {
            base.WriteCommand(command, dataOut);
            MessageId info = (MessageId) command;
            writeObject(info.getProducerId(), dataOut);
            dataOut.writeLong(info.getProducerSequenceId());
            dataOut.writeLong(info.getBrokerSequenceId());

        }
    }
}
