//
// Marshalling code for Open Wire Format for MessageDispatch
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;
using System.IO;

using OpenWire.Core;
using OpenWire.Core.Commands;
using OpenWire.Core.IO;

namespace OpenWire.Core.IO
{
    public class MessageDispatchMarshaller : AbstractCommandMarshaller
    {

        public override Command CreateCommand() {
            return new MessageDispatch();
        }

        public override void BuildCommand(Command command, BinaryReader dataIn) {
            base.BuildCommand(command, dataIn);
            MessageDispatch info = (MessageDispatch) command;
            info.setConsumerId((org.apache.activemq.command.ConsumerId) readObject(dataIn));
            info.setDestination((org.apache.activemq.command.ActiveMQDestination) readObject(dataIn));
            info.setMessage((org.apache.activemq.command.Message) readObject(dataIn));
            info.setRedeliveryCounter(dataIn.readInt());

        }

        public override void WriteCommand(Command command, BinaryWriter dataOut) {
            base.WriteCommand(command, dataOut);
            MessageDispatch info = (MessageDispatch) command;
            writeObject(info.getConsumerId(), dataOut);
            writeObject(info.getDestination(), dataOut);
            writeObject(info.getMessage(), dataOut);
            dataOut.writeInt(info.getRedeliveryCounter());

        }
    }
}
