//
// Marshalling code for Open Wire Format for SubscriptionInfo
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;
using System.IO;

using OpenWire.Core;
using OpenWire.Core.Commands;
using OpenWire.Core.IO;

namespace OpenWire.Core.IO
{
    public class SubscriptionInfoMarshaller : AbstractCommandMarshaller
    {


        public override Command CreateCommand() {
            return new SubscriptionInfo();
        }

        public override void BuildCommand(Command command, BinaryReader dataIn) {
            base.BuildCommand(command, dataIn);

            SubscriptionInfo info = (SubscriptionInfo) command;
            info.ClientId = dataIn.ReadString();
            info.Destination = ReadDestination(dataIn);
            info.Selector = dataIn.ReadString();
            info.SubcriptionName = dataIn.ReadString();

        }

        public override void WriteCommand(Command command, BinaryWriter dataOut) {
            base.WriteCommand(command, dataOut);

            SubscriptionInfo info = (SubscriptionInfo) command;
            dataOut.Write(info.ClientId);
            WriteDestination(info.Destination, dataOut);
            dataOut.Write(info.Selector);
            dataOut.Write(info.SubcriptionName);

        }
    }
}
