/*
* Copyright 2006 The Apache Software Foundation or its licensors, as
* applicable.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef DestinationInfo_hpp_
#define DestinationInfo_hpp_

#include <string>
#include "command/BaseCommand.hpp"
    
#include "command/ConnectionId.hpp"
#include "command/ActiveMQDestination.hpp"
#include "command/BrokerId.hpp"

#include "util/ifr/ap.hpp"
#include "util/ifr/p.hpp"

namespace apache
{
  namespace activemq
  {
    namespace client
    {
      namespace command
      {
        using namespace ifr;
        using namespace std;
        using namespace apache::activemq::client;

/*
 *
 *  Marshalling code for Open Wire Format for DestinationInfo
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
class DestinationInfo : public BaseCommand
{
private:
    p<ConnectionId> connectionId ;
    p<ActiveMQDestination> destination ;
    char operationType ;
    long long timeout ;
    ap<BrokerId> brokerPath ;

public:
    const static int TYPE = 8;

public:
    DestinationInfo() ;
    virtual ~DestinationInfo() ;

    virtual int getCommandType() ;

    virtual p<ConnectionId> getConnectionId() ;
    virtual void setConnectionId(p<ConnectionId> connectionId) ;

    virtual p<ActiveMQDestination> getDestination() ;
    virtual void setDestination(p<ActiveMQDestination> destination) ;

    virtual char getOperationType() ;
    virtual void setOperationType(char operationType) ;

    virtual long long getTimeout() ;
    virtual void setTimeout(long long timeout) ;

    virtual ap<BrokerId> getBrokerPath() ;
    virtual void setBrokerPath(ap<BrokerId> brokerPath) ;


} ;

/* namespace */
      }
    }
  }
}

#endif /*DestinationInfo_hpp_*/
