/*
* Copyright 2006 The Apache Software Foundation or its licensors, as
* applicable.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include "command/DestinationInfo.hpp"

using namespace apache::activemq::client::command;

/*
 *
 *  Marshalling code for Open Wire Format for DestinationInfo
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
DestinationInfo::DestinationInfo()
{
    this->connectionId = NULL ;
    this->destination = NULL ;
    this->operationType = NULL ;
    this->timeout = NULL ;
    this->brokerPath = NULL ;
}

DestinationInfo::~DestinationInfo()
{
}

        
p<ConnectionId> DestinationInfo::getConnectionId()
{
    return connectionId ;
}

void DestinationInfo::setConnectionId(p<ConnectionId> connectionId)
{
    this->connectionId = connectionId ;
}

        
ActiveMQDestination DestinationInfo::getDestination()
{
    return destination ;
}

void DestinationInfo::setDestination(ActiveMQDestination destination)
{
    this->destination = destination ;
}

        
byte DestinationInfo::getOperationType()
{
    return operationType ;
}

void DestinationInfo::setOperationType(byte operationType)
{
    this->operationType = operationType ;
}

        
long DestinationInfo::getTimeout()
{
    return timeout ;
}

void DestinationInfo::setTimeout(long timeout)
{
    this->timeout = timeout ;
}

        
BrokerId[] DestinationInfo::getBrokerPath()
{
    return brokerPath ;
}

void DestinationInfo::setBrokerPath(BrokerId[] brokerPath)
{
    this->brokerPath = brokerPath ;
}
