//
// Marshalling code for Open Wire Format for ConnectionError
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;

using OpenWire.Client;
using OpenWire.Client.Core;

namespace OpenWire.Client.Commands
{
    public class ConnectionError : BaseCommand
    {
    			public const byte ID_ConnectionError = 16;
    			
        BrokerError exception;
        ConnectionId connectionId;



        // TODO generate Equals method
        // TODO generate GetHashCode method
        // TODO generate ToString method


        public override byte GetCommandType() {
            return ID_ConnectionError;
        }


        // Properties

        public BrokerError Exception
        {
            get { return exception; }
            set { this.exception = value; }            
        }

        public ConnectionId ConnectionId
        {
            get { return connectionId; }
            set { this.connectionId = value; }            
        }

    }
}
