//
// Marshalling code for Open Wire Format for DestinationInfo
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;

using OpenWire.Client;
using OpenWire.Client.Core;

namespace OpenWire.Client.Commands
{
    public class DestinationInfo : BaseCommand
    {
    			public const byte ID_DestinationInfo = 8;
    			
        ConnectionId connectionId;
        ActiveMQDestination destination;
        byte operationType;
        long timeout;
        BrokerId[] brokerPath;



        // TODO generate Equals method
        // TODO generate GetHashCode method
        // TODO generate ToString method


        public override byte GetCommandType() {
            return ID_DestinationInfo;
        }


        // Properties

        public ConnectionId ConnectionId
        {
            get { return connectionId; }
            set { this.connectionId = value; }            
        }

        public ActiveMQDestination Destination
        {
            get { return destination; }
            set { this.destination = value; }            
        }

        public byte OperationType
        {
            get { return operationType; }
            set { this.operationType = value; }            
        }

        public long Timeout
        {
            get { return timeout; }
            set { this.timeout = value; }            
        }

        public BrokerId[] BrokerPath
        {
            get { return brokerPath; }
            set { this.brokerPath = value; }            
        }

    }
}
