//
// Marshalling code for Open Wire Format for ActiveMQDestination
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;

using OpenWire.Core;

namespace OpenWire.Core.Commands
{
    public class ActiveMQDestination : AbstractCommand
    {
    			public const int ID_ActiveMQDestination = 1;
    			
        string physicalName;



        // TODO generate Equals method
        // TODO generate GetHashCode method
        // TODO generate ToString method


        public override int GetCommandType() {
            return ID_ActiveMQDestination;
        }


        // Properties

        public string PhysicalName
        {
            get
            {
                return physicalName;
            }
            set
            {
                physicalName = value;
            }            
        }

    }
}
