//
// Marshalling code for Open Wire Format for ConnectionInfo
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;

using OpenWire.Core;

namespace OpenWire.Core.Commands
{
    public class ConnectionInfo : BaseCommand
    {
    			public const byte ID_ConnectionInfo = 3;
    			
        ConnectionId connectionId;
        string clientId;
        string password;
        string userName;
        BrokerId[] brokerPath;



        // TODO generate Equals method
        // TODO generate GetHashCode method
        // TODO generate ToString method


        public override byte GetCommandType() {
            return ID_ConnectionInfo;
        }


        // Properties

        public ConnectionId ConnectionId
        {
            get
            {
                return connectionId;
            }
            set
            {
                connectionId = value;
            }            
        }

        public string ClientId
        {
            get
            {
                return clientId;
            }
            set
            {
                clientId = value;
            }            
        }

        public string Password
        {
            get
            {
                return password;
            }
            set
            {
                password = value;
            }            
        }

        public string UserName
        {
            get
            {
                return userName;
            }
            set
            {
                userName = value;
            }            
        }

        public BrokerId[] BrokerPath
        {
            get
            {
                return brokerPath;
            }
            set
            {
                brokerPath = value;
            }            
        }

    }
}
