//
// Marshalling code for Open Wire Format for ControlCommand
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;

using OpenWire.Core;

namespace OpenWire.Core.Commands
{
    public class ControlCommand : AbstractCommand
    {
        string command;



        // TODO generate Equals method
        // TODO generate GetHashCode method
        // TODO generate ToString method


        public override int GetCommandType() {
            return 1;
        }


        // Properties

        public string Command
        {
            get
            {
                return command;
            }
            set
            {
                command = value;
            }            
        }

    }
}
