//
// Marshalling code for Open Wire Format for DataResponse
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;

using OpenWire.Core;

namespace OpenWire.Core.Commands
{
    public class DataResponse : Response
    {
    			public const byte ID_DataResponse = 32;
    			
        DataStructure data;



        // TODO generate Equals method
        // TODO generate GetHashCode method
        // TODO generate ToString method


        public override byte GetCommandType() {
            return ID_DataResponse;
        }


        // Properties

        public DataStructure Data
        {
            get
            {
                return data;
            }
            set
            {
                data = value;
            }            
        }

    }
}
