//
// Marshalling code for Open Wire Format for DestinationInfo
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;

using OpenWire.Core;

namespace OpenWire.Core.Commands
{
    public class DestinationInfo : BaseCommand
    {
    			public const byte ID_DestinationInfo = 8;
    			
        ConnectionId connectionId;
        ActiveMQDestination destination;
        byte operationType;
        long timeout;
        BrokerId[] brokerPath;



        // TODO generate Equals method
        // TODO generate GetHashCode method
        // TODO generate ToString method


        public override byte GetCommandType() {
            return ID_DestinationInfo;
        }


        // Properties

        public ConnectionId ConnectionId
        {
            get
            {
                return connectionId;
            }
            set
            {
                connectionId = value;
            }            
        }

        public ActiveMQDestination Destination
        {
            get
            {
                return destination;
            }
            set
            {
                destination = value;
            }            
        }

        public byte OperationType
        {
            get
            {
                return operationType;
            }
            set
            {
                operationType = value;
            }            
        }

        public long Timeout
        {
            get
            {
                return timeout;
            }
            set
            {
                timeout = value;
            }            
        }

        public BrokerId[] BrokerPath
        {
            get
            {
                return brokerPath;
            }
            set
            {
                brokerPath = value;
            }            
        }

    }
}
