//
// Marshalling code for Open Wire Format for JournalTransaction
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;

using OpenWire.Core;

namespace OpenWire.Core.Commands
{
    public class JournalTransaction : AbstractCommand
    {
        TransactionId transactionId;
        byte type;
        bool wasPrepared;



        // TODO generate Equals method
        // TODO generate GetHashCode method
        // TODO generate ToString method


        public override int GetCommandType() {
            return 1;
        }


        // Properties

        public TransactionId TransactionId
        {
            get
            {
                return transactionId;
            }
            set
            {
                transactionId = value;
            }            
        }

        public byte Type
        {
            get
            {
                return type;
            }
            set
            {
                type = value;
            }            
        }

        public bool WasPrepared
        {
            get
            {
                return wasPrepared;
            }
            set
            {
                wasPrepared = value;
            }            
        }

    }
}
