//
// Marshalling code for Open Wire Format for RemoveInfo
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;

using OpenWire.Core;

namespace OpenWire.Core.Commands
{
    public class RemoveInfo : AbstractCommand
    {
        Command objectId;



        // TODO generate Equals method
        // TODO generate HashCode method
        // TODO generate ToString method


        public override int GetCommandType() {
            return 1;
        }


        // Properties


        public Command ObjectId
        {
            get
            {
                return objectId;
            }
            set
            {
                objectId = value;
            }            
        }

    }
}
