/*
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
*/

#include "command/ConsumerControl.h"

using namespace ActiveMQ::Command;

/*
 *
 *  Marshalling code for Open Wire Format for ConsumerControl
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
bool
ConsumerControl::isMarshalAware() const
{
    return false;
}

ConsumerControl::ConsumerControl()
{
    close_ = 0;
    prefetch_ = 0;
}

int
ConsumerControl::getCommandType() const
{
    return TYPE;
}

ConsumerControl::~ConsumerControl()
{
}

bool ConsumerControl::isClose() const
{
    return close_;
}

void ConsumerControl::setClose(bool close)
{
    close_ = close;
}

boost::shared_ptr<const ConsumerId> ConsumerControl::getConsumerId() const
{
    return consumerId_;
}

void ConsumerControl::setConsumerId(const boost::shared_ptr<ConsumerId>& consumerId)
{
    consumerId_ = consumerId;
}

int ConsumerControl::getPrefetch() const
{
    return prefetch_;
}

void ConsumerControl::setPrefetch(int prefetch)
{
    prefetch_ = prefetch;
}
