/*
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
*/

#include "command/JournalTopicAck.h"

using namespace ActiveMQ::Command;

/*
 *
 *  Marshalling code for Open Wire Format for JournalTopicAck
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
bool
JournalTopicAck::isMarshalAware() const
{
    return false;
}

JournalTopicAck::JournalTopicAck()
{
    messageSequenceId_ = 0;
    subscritionName_ = "";
    clientId_ = "";
}

int
JournalTopicAck::getCommandType() const
{
    return TYPE;
}

JournalTopicAck::~JournalTopicAck()
{
}

boost::shared_ptr<const ActiveMQDestination> JournalTopicAck::getDestination() const
{
    return destination_;
}

void JournalTopicAck::setDestination(const boost::shared_ptr<ActiveMQDestination>& destination)
{
    destination_ = destination;
}

boost::shared_ptr<const MessageId> JournalTopicAck::getMessageId() const
{
    return messageId_;
}

void JournalTopicAck::setMessageId(const boost::shared_ptr<MessageId>& messageId)
{
    messageId_ = messageId;
}

int64_t JournalTopicAck::getMessageSequenceId() const
{
    return messageSequenceId_;
}

void JournalTopicAck::setMessageSequenceId(int64_t messageSequenceId)
{
    messageSequenceId_ = messageSequenceId;
}

const std::string& JournalTopicAck::getSubscritionName() const
{
    return subscritionName_;
}

void JournalTopicAck::setSubscritionName(const std::string& subscritionName)
{
    subscritionName_ = subscritionName;
}

const std::string& JournalTopicAck::getClientId() const
{
    return clientId_;
}

void JournalTopicAck::setClientId(const std::string& clientId)
{
    clientId_ = clientId;
}

boost::shared_ptr<const TransactionId> JournalTopicAck::getTransactionId() const
{
    return transactionId_;
}

void JournalTopicAck::setTransactionId(const boost::shared_ptr<TransactionId>& transactionId)
{
    transactionId_ = transactionId;
}
