/*
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
*/

#ifndef JournalTransaction_h_
#define JournalTransaction_h_

#include <string>
#include <vector>
#include <exception>
#include <inttypes.h>
#include <boost/shared_ptr.hpp>

#include "command/AbstractCommand.h"    
#include "TransactionId.h"

namespace ActiveMQ {
  namespace Command {

    /*
     *
     *  Marshalling code for Open Wire Format for JournalTransaction
     *
     *
     *  NOTE!: This file is autogenerated - do not modify!
     *         if you need to make a change, please see the Groovy scripts in the
     *         activemq-core module
     *
     */
    class JournalTransaction : public AbstractCommand
    {
      private:
        boost::shared_ptr<const TransactionId> transactionId_;
        uint8_t type_;
        bool wasPrepared_;

      public:
        const static int TYPE = 54;
    
      public:
        JournalTransaction();
        virtual ~JournalTransaction();
    
        virtual bool isMarshalAware() const;
        virtual int getCommandType() const;

        virtual boost::shared_ptr<const TransactionId> getTransactionId() const;
        virtual void setTransactionId(const boost::shared_ptr<TransactionId>& transactionId);

        virtual uint8_t getType() const;
        virtual void setType(uint8_t type);

        virtual bool getWasPrepared() const;
        virtual void setWasPrepared(bool wasPrepared);
    };
  }
}

#endif /*JournalTransaction_h_*/
