/*
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
*/

#include "command/JournalTrace.h"

using namespace ActiveMQ::Command;

/*
 *
 *  Marshalling code for Open Wire Format for JournalTrace
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
bool
JournalTrace::isMarshalAware() const
{
    return false;
}

JournalTrace::JournalTrace()
{
    message_ = "";
}

int
JournalTrace::getCommandType() const
{
    return TYPE;
}

JournalTrace::~JournalTrace()
{
}

const std::string& JournalTrace::getMessage() const
{
    return message_;
}

void JournalTrace::setMessage(const std::string& message)
{
    message_ = message;
}
