/*
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
*/

#include "command/MessageAck.h"

using namespace ActiveMQ::Command;

/*
 *
 *  Marshalling code for Open Wire Format for MessageAck
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
bool
MessageAck::isMarshalAware() const
{
    return false;
}

MessageAck::MessageAck()
{
    ackType_ = 0;
    messageCount_ = 0;
}

int
MessageAck::getCommandType() const
{
    return TYPE;
}

MessageAck::~MessageAck()
{
}

boost::shared_ptr<const ActiveMQDestination> MessageAck::getDestination() const
{
    return destination_;
}

void MessageAck::setDestination(const boost::shared_ptr<ActiveMQDestination>& destination)
{
    destination_ = destination;
}

boost::shared_ptr<const TransactionId> MessageAck::getTransactionId() const
{
    return transactionId_;
}

void MessageAck::setTransactionId(const boost::shared_ptr<TransactionId>& transactionId)
{
    transactionId_ = transactionId;
}

boost::shared_ptr<const ConsumerId> MessageAck::getConsumerId() const
{
    return consumerId_;
}

void MessageAck::setConsumerId(const boost::shared_ptr<ConsumerId>& consumerId)
{
    consumerId_ = consumerId;
}

uint8_t MessageAck::getAckType() const
{
    return ackType_;
}

void MessageAck::setAckType(uint8_t ackType)
{
    ackType_ = ackType;
}

boost::shared_ptr<const MessageId> MessageAck::getFirstMessageId() const
{
    return firstMessageId_;
}

void MessageAck::setFirstMessageId(const boost::shared_ptr<MessageId>& firstMessageId)
{
    firstMessageId_ = firstMessageId;
}

boost::shared_ptr<const MessageId> MessageAck::getLastMessageId() const
{
    return lastMessageId_;
}

void MessageAck::setLastMessageId(const boost::shared_ptr<MessageId>& lastMessageId)
{
    lastMessageId_ = lastMessageId;
}

int MessageAck::getMessageCount() const
{
    return messageCount_;
}

void MessageAck::setMessageCount(int messageCount)
{
    messageCount_ = messageCount;
}
