/*
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
*/

#include "command/SubscriptionInfo.h"

using namespace ActiveMQ::Command;

/*
 *
 *  Marshalling code for Open Wire Format for SubscriptionInfo
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
bool
SubscriptionInfo::isMarshalAware() const
{
    return false;
}

SubscriptionInfo::SubscriptionInfo()
{
    clientId_ = "";
    selector_ = "";
    subcriptionName_ = "";
}

int
SubscriptionInfo::getCommandType() const
{
    return TYPE;
}

SubscriptionInfo::~SubscriptionInfo()
{
}

const std::string& SubscriptionInfo::getClientId() const
{
    return clientId_;
}

void SubscriptionInfo::setClientId(const std::string& clientId)
{
    clientId_ = clientId;
}

boost::shared_ptr<const ActiveMQDestination> SubscriptionInfo::getDestination() const
{
    return destination_;
}

void SubscriptionInfo::setDestination(const boost::shared_ptr<ActiveMQDestination>& destination)
{
    destination_ = destination;
}

const std::string& SubscriptionInfo::getSelector() const
{
    return selector_;
}

void SubscriptionInfo::setSelector(const std::string& selector)
{
    selector_ = selector;
}

const std::string& SubscriptionInfo::getSubcriptionName() const
{
    return subcriptionName_;
}

void SubscriptionInfo::setSubcriptionName(const std::string& subcriptionName)
{
    subcriptionName_ = subcriptionName;
}
