/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.activemq.maven.xbean;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.TreeMap;

import org.apache.xbean.spring.generator.XmlMetadataGenerator;

/**
 * Writes {@code META-INF/spring.handlers} and {@code META-INF/spring.schemas}
 * with the same escaping and header xbean-spring uses, minus the date comment
 * that {@link Properties#store} adds, so two builds of the same sources give the
 * same bytes. Entries are sorted and lines end with a newline on every platform.
 */
public final class SpringMetadataWriter {

    static final String HEADER = "Generated by xbean-spring";

    private SpringMetadataWriter() {
    }

    /** maps the namespace to xbean-spring's Spring namespace handler */
    public static File writeHandlers(File metaInfDir, String namespace) throws IOException {
        File file = new File(metaInfDir, "META-INF/spring.handlers");
        merge(file, namespace, XmlMetadataGenerator.NAMESPACE_HANDLER);
        return file;
    }

    /** maps the schema location under the namespace to the schema's classpath location */
    public static File writeSchemas(File metaInfDir, String namespace, File schema) throws IOException {
        File file = new File(metaInfDir, "META-INF/spring.schemas");
        String location = metaInfDir.toURI().relativize(schema.toURI()).toString();
        String uri = namespace.endsWith("/") ? namespace : namespace + "/";
        merge(file, uri + location, location);
        return file;
    }

    private static void merge(File file, String key, String value) throws IOException {
        Properties properties = new SortedProperties();
        if (file.exists()) {
            try (InputStream in = Files.newInputStream(file.toPath())) {
                properties.load(in);
            }
        }
        properties.put(key, value);
        file.getParentFile().mkdirs();
        Files.writeString(file.toPath(), render(properties), StandardCharsets.ISO_8859_1);
    }

    static String render(Properties properties) throws IOException {
        var out = new StringWriter();
        properties.store(out, HEADER);
        String[] lines = out.toString().split("\\R");
        var text = new StringBuilder();
        for (int i = 0; i < lines.length; i++) {
            // the second line is the date Properties.store insists on; keep the marker, drop the time
            text.append(i == 1 ? "#" : lines[i]).append('\n');
        }
        return text.toString();
    }

    /** Properties.store iterates entrySet(), so a sorted view makes the output order fixed. */
    private static final class SortedProperties extends Properties {
        private static final long serialVersionUID = 1L;

        @Override
        public synchronized Set<Map.Entry<Object, Object>> entrySet() {
            var sorted = new TreeMap<Object, Object>(Comparator.comparing(Object::toString));
            for (Map.Entry<Object, Object> entry : super.entrySet()) {
                sorted.put(entry.getKey(), entry.getValue());
            }
            return new LinkedHashSet<>(sorted.entrySet());
        }
    }
}
