//
// Marshalling code for Open Wire Format for RemoveSubscriptionInfo
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;
using System.IO;

using OpenWire.Client;
using OpenWire.Client.Commands;
using OpenWire.Client.Core;
using OpenWire.Client.IO;

namespace OpenWire.Client.IO
{
    public class RemoveSubscriptionInfoMarshaller : AbstractCommandMarshaller
    {


        public override Command CreateCommand() {
            return new RemoveSubscriptionInfo();
        }

        public override void BuildCommand(Command command, BinaryReader dataIn) {
            base.BuildCommand(command, dataIn);

            RemoveSubscriptionInfo info = (RemoveSubscriptionInfo) command;
            info.ConnectionId = (ConnectionId) CommandMarshallerRegistry.ConnectionIdMarshaller.ReadCommand(dataIn);
            info.SubcriptionName = dataIn.ReadString();
            info.ClientId = dataIn.ReadString();

        }

        public override void WriteCommand(Command command, BinaryWriter dataOut) {
            base.WriteCommand(command, dataOut);

            RemoveSubscriptionInfo info = (RemoveSubscriptionInfo) command;
            CommandMarshallerRegistry.ConnectionIdMarshaller.WriteCommand(info.ConnectionId, dataOut);
            dataOut.Write(info.SubcriptionName);
            dataOut.Write(info.ClientId);

        }
    }
}
