## ---------------------------------------------------------------------------
## Licensed to the Apache Software Foundation (ASF) under one or more
## contributor license agreements.  See the NOTICE file distributed with
## this work for additional information regarding copyright ownership.
## The ASF licenses this file to You under the Apache License, Version 2.0
## (the "License"); you may not use this file except in compliance with
## the License.  You may obtain a copy of the License at
## 
## http://www.apache.org/licenses/LICENSE-2.0
## 
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
## ---------------------------------------------------------------------------

# Defines credentials that will be used by components (like web console) to access the broker
#
# Values are created with: activemq encrypt --password <encryptionPassword> --input <value>
# (the values below encrypt "manager" and "password" with the encryption password "activemq")
# Values encrypted with jasypt by previous releases are still supported.

activemq.username=system
activemq.password=ENC(v2:210000:ZWgS5JLey0+REhs5B3j94A==:k7P8578K8dlx3VF8:Ph8Y0gWoYQMuUmgg9HJ2ZH/qy6TvkFA=)
guest.password=ENC(v2:210000:Fq/mUvj2ifNAWjYGTvlZTw==:HyckEQFQXETKt8Up:PDU3nu9EFyfBiXcCRMKcBByugR0yR0WY)