/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.activemq.jaas;

import java.security.Principal;
import java.util.Objects;

/**
 * Principal describing the connection that was authenticated. Its name is the
 * connection id, which identifies the connection uniquely; it also carries the
 * clientId the connection was permitted to use, if it presented one, whether the
 * user's rule allows it to act as a network connection, whether it arrived over
 * SSL/TLS, its remote address and the transport connector that accepted it.
 *
 * <p>The connection id is generated by the client from its host name, port and a
 * counter (bridges prefix it with the broker names). It is unique but not
 * verified by the broker, so it identifies the connection and must not be the
 * basis of an authorization decision.
 *
 * <p>Added to the Subject alongside the {@link UserPrincipal} whenever clientId
 * authorization is enabled on the login module, so the broker can hold a
 * connection to the network decision even if it declares itself a network
 * connection after authenticating. Its absence means the feature is not
 * configured.
 */
public class ConnectionPrincipal implements Principal {

    private final String connectionId;
    private final String clientId;
    private final boolean networkConnection;
    private final boolean ssl;
    private final String remoteAddress;
    private final String transportConnectorName;
    private transient int hash;

    public ConnectionPrincipal(String connectionId, String clientId, boolean networkConnection) {
        this(connectionId, clientId, networkConnection, false, null, null);
    }

    public ConnectionPrincipal(String connectionId, String clientId, boolean networkConnection, boolean ssl,
            String remoteAddress, String transportConnectorName) {
        this.connectionId = connectionId;
        this.clientId = clientId;
        this.networkConnection = networkConnection;
        this.ssl = ssl;
        this.remoteAddress = remoteAddress;
        this.transportConnectorName = transportConnectorName;
    }

    /** true when the connection was accepted over SSL/TLS */
    public boolean isSsl() {
        return ssl;
    }

    /** the client's remote address as seen by the transport, or null when unknown */
    public String getRemoteAddress() {
        return remoteAddress;
    }

    /** the name of the transport connector that accepted the connection, or null when unknown */
    public String getTransportConnectorName() {
        return transportConnectorName;
    }

    /** the connection id assigned by the client, or null when the callback handler did not supply one */
    public String getConnectionId() {
        return connectionId;
    }

    /** the clientId the connection presented and was allowed, or null when it set none */
    public String getClientId() {
        return clientId;
    }

    /** true when the user's rule permits this connection to be a network connection */
    public boolean isNetworkConnection() {
        return networkConnection;
    }

    /** the connection id, or an empty string when none was supplied */
    @Override
    public String getName() {
        return connectionId != null ? connectionId : "";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final ConnectionPrincipal that = (ConnectionPrincipal) o;
        return networkConnection == that.networkConnection
                && ssl == that.ssl
                && Objects.equals(connectionId, that.connectionId)
                && Objects.equals(clientId, that.clientId)
                && Objects.equals(remoteAddress, that.remoteAddress)
                && Objects.equals(transportConnectorName, that.transportConnectorName);
    }

    @Override
    public int hashCode() {
        if (hash == 0) {
            hash = Objects.hash(connectionId, clientId, networkConnection, ssl, remoteAddress, transportConnectorName);
        }
        return hash;
    }

    @Override
    public String toString() {
        return getName()
                + (clientId != null ? " clientId=" + clientId : "")
                + (transportConnectorName != null ? " connector=" + transportConnectorName : "")
                + (remoteAddress != null ? " from " + remoteAddress : "")
                + (ssl ? " [ssl]" : "")
                + (networkConnection ? " [networkConnection]" : "");
    }
}
