/*
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#ifndef ActiveMQ_BrokerInfo_hpp_
#define ActiveMQ_BrokerInfo_hpp_

// Turn off warning message for ignored exception specification
#ifdef _MSC_VER
#pragma warning( disable : 4290 )
#endif

#include <string>
#include "activemq/command/BaseCommand.hpp"
#include "activemq/command/BrokerId.hpp"
#include "activemq/command/BrokerInfo.hpp"

#include "activemq/protocol/IMarshaller.hpp"
#include "ppr/io/IOutputStream.hpp"
#include "ppr/io/IInputStream.hpp"
#include "ppr/io/IOException.hpp"
#include "ppr/util/ifr/array"
#include "ppr/util/ifr/p"

namespace apache
{
  namespace activemq
  {
    namespace command
    {
      using namespace ifr;
      using namespace std;
      using namespace apache::activemq;
      using namespace apache::activemq::protocol;
      using namespace apache::ppr::io;

/*
 *
 *  Command and marshalling code for OpenWire format for BrokerInfo
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
class BrokerInfo : public BaseCommand
{
protected:
    p<BrokerId> brokerId ;
    p<string> brokerURL ;
    array<BrokerInfo> peerBrokerInfos ;
    p<string> brokerName ;
    bool slaveBroker ;
    bool masterBroker ;
    bool faultTolerantConfiguration ;

public:
    const static unsigned char TYPE = 2;

public:
    BrokerInfo() ;
    virtual ~BrokerInfo() ;

    virtual unsigned char getDataStructureType() ;

    virtual p<BrokerId> getBrokerId() ;
    virtual void setBrokerId(p<BrokerId> brokerId) ;

    virtual p<string> getBrokerURL() ;
    virtual void setBrokerURL(p<string> brokerURL) ;

    virtual array<BrokerInfo> getPeerBrokerInfos() ;
    virtual void setPeerBrokerInfos(array<BrokerInfo> peerBrokerInfos) ;

    virtual p<string> getBrokerName() ;
    virtual void setBrokerName(p<string> brokerName) ;

    virtual bool getSlaveBroker() ;
    virtual void setSlaveBroker(bool slaveBroker) ;

    virtual bool getMasterBroker() ;
    virtual void setMasterBroker(bool masterBroker) ;

    virtual bool getFaultTolerantConfiguration() ;
    virtual void setFaultTolerantConfiguration(bool faultTolerantConfiguration) ;

    virtual int marshal(p<IMarshaller> marshaller, int mode, p<IOutputStream> ostream) throw (IOException) ;
    virtual void unmarshal(p<IMarshaller> marshaller, int mode, p<IInputStream> istream) throw (IOException) ;
} ;

/* namespace */
    }
  }
}

#endif /*ActiveMQ_BrokerInfo_hpp_*/
