/*
* Copyright 2006 The Apache Software Foundation or its licensors, as
* applicable.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#ifndef ActiveMQ_ConnectionInfo_hpp_
#define ActiveMQ_ConnectionInfo_hpp_

// Turn off warning message for ignored exception specification
#ifdef _MSC_VER
#pragma warning( disable : 4290 )
#endif

#include <string>
#include "activemq/command/BaseCommand.hpp"
#include "activemq/command/ConnectionId.hpp"
#include "activemq/command/BrokerId.hpp"

#include "activemq/protocol/IMarshaller.hpp"
#include "ppr/io/IOutputStream.hpp"
#include "ppr/io/IInputStream.hpp"
#include "ppr/io/IOException.hpp"
#include "ppr/util/ifr/array"
#include "ppr/util/ifr/p"

namespace apache
{
  namespace activemq
  {
    namespace command
    {
      using namespace ifr;
      using namespace std;
      using namespace apache::activemq;
      using namespace apache::activemq::protocol;
      using namespace apache::ppr::io;

/*
 *
 *  Command and marshalling code for OpenWire format for ConnectionInfo
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
class ConnectionInfo : public BaseCommand
{
protected:
    p<ConnectionId> connectionId ;
    p<string> clientId ;
    p<string> password ;
    p<string> userName ;
    array<BrokerId> brokerPath ;
    bool brokerMasterConnector ;
    bool manageable ;

public:
    const static unsigned char TYPE = 3;

public:
    ConnectionInfo() ;
    virtual ~ConnectionInfo() ;

    virtual unsigned char getDataStructureType() ;

    virtual p<ConnectionId> getConnectionId() ;
    virtual void setConnectionId(p<ConnectionId> connectionId) ;

    virtual p<string> getClientId() ;
    virtual void setClientId(p<string> clientId) ;

    virtual p<string> getPassword() ;
    virtual void setPassword(p<string> password) ;

    virtual p<string> getUserName() ;
    virtual void setUserName(p<string> userName) ;

    virtual array<BrokerId> getBrokerPath() ;
    virtual void setBrokerPath(array<BrokerId> brokerPath) ;

    virtual bool getBrokerMasterConnector() ;
    virtual void setBrokerMasterConnector(bool brokerMasterConnector) ;

    virtual bool getManageable() ;
    virtual void setManageable(bool manageable) ;

    virtual int marshal(p<IMarshaller> marshaller, int mode, p<IOutputStream> ostream) throw (IOException) ;
    virtual void unmarshal(p<IMarshaller> marshaller, int mode, p<IInputStream> istream) throw (IOException) ;
} ;

/* namespace */
    }
  }
}

#endif /*ActiveMQ_ConnectionInfo_hpp_*/
