/*
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include "activemq/command/ConnectionError.hpp"

using namespace apache::activemq::command;

/*
 *
 *  Command and marshalling code for OpenWire format for ConnectionError
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
ConnectionError::ConnectionError()
{
    this->exception = NULL ;
    this->connectionId = NULL ;
}

ConnectionError::~ConnectionError()
{
}

unsigned char ConnectionError::getDataStructureType()
{
    return ConnectionError::TYPE ; 
}

        
p<BrokerError> ConnectionError::getException()
{
    return exception ;
}

void ConnectionError::setException(p<BrokerError> exception)
{
    this->exception = exception ;
}

        
p<ConnectionId> ConnectionError::getConnectionId()
{
    return connectionId ;
}

void ConnectionError::setConnectionId(p<ConnectionId> connectionId)
{
    this->connectionId = connectionId ;
}

int ConnectionError::marshal(p<IMarshaller> marshaller, int mode, p<IOutputStream> ostream) throw (IOException)
{
    int size = 0 ;

    size += BaseCommand::marshal(marshaller, mode, ostream) ; 
    size += marshaller->marshalObject(exception, mode, ostream) ; 
    size += marshaller->marshalObject(connectionId, mode, ostream) ; 
    return size ;
}

void ConnectionError::unmarshal(p<IMarshaller> marshaller, int mode, p<IInputStream> istream) throw (IOException)
{
    BaseCommand::unmarshal(marshaller, mode, istream) ; 
    exception = p_cast<BrokerError>(marshaller->unmarshalObject(mode, istream)) ; 
    connectionId = p_cast<ConnectionId>(marshaller->unmarshalObject(mode, istream)) ; 
}
