/*
* Licensed to the Apache Software Foundation (ASF) under one or more
* contributor license agreements.  See the NOTICE file distributed with
* this work for additional information regarding copyright ownership.
* The ASF licenses this file to You under the Apache License, Version 2.0
* (the "License"); you may not use this file except in compliance with
* the License.  You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include "activemq/command/DiscoveryEvent.hpp"

using namespace apache::activemq::command;

/*
 *
 *  Marshalling code for Open Wire Format for DiscoveryEvent
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
DiscoveryEvent::DiscoveryEvent()
{
    this->serviceName = NULL ;
    this->brokerName = NULL ;
}

DiscoveryEvent::~DiscoveryEvent()
{
}

unsigned char DiscoveryEvent::getDataStructureType()
{
    return DiscoveryEvent::TYPE ; 
}

        
p<string> DiscoveryEvent::getServiceName()
{
    return serviceName ;
}

void DiscoveryEvent::setServiceName(p<string> serviceName)
{
    this->serviceName = serviceName ;
}

        
p<string> DiscoveryEvent::getBrokerName()
{
    return brokerName ;
}

void DiscoveryEvent::setBrokerName(p<string> brokerName)
{
    this->brokerName = brokerName ;
}

int DiscoveryEvent::marshal(p<IMarshaller> marshaller, int mode, p<IOutputStream> writer) throw (IOException)
{
    int size = 0 ;

    size += marshaller->marshalInt(commandId, mode, writer) ;
    size += marshaller->marshalBoolean(responseRequired, mode, writer) ; 
    size += marshaller->marshalString(serviceName, mode, writer) ; 
    size += marshaller->marshalString(brokerName, mode, writer) ; 
    return size ;
}

void DiscoveryEvent::unmarshal(p<IMarshaller> marshaller, int mode, p<IInputStream> reader) throw (IOException)
{
    commandId = marshaller->unmarshalInt(mode, reader) ;
    responseRequired = marshaller->unmarshalBoolean(mode, reader) ; 
    serviceName = p_cast<string>(marshaller->unmarshalString(mode, reader)) ; 
    brokerName = p_cast<string>(marshaller->unmarshalString(mode, reader)) ; 
}
