/*
* Copyright 2006 The Apache Software Foundation or its licensors, as
* applicable.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include "activemq/command/IntegerResponse.hpp"

using namespace apache::activemq::command;

/*
 *
 *  Marshalling code for Open Wire Format for IntegerResponse
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
IntegerResponse::IntegerResponse()
{
    this->result = 0 ;
}

IntegerResponse::~IntegerResponse()
{
}

unsigned char IntegerResponse::getDataStructureType()
{
    return IntegerResponse::TYPE ; 
}

        
int IntegerResponse::getResult()
{
    return result ;
}

void IntegerResponse::setResult(int result)
{
    this->result = result ;
}

int IntegerResponse::marshal(p<IMarshaller> marshaller, int mode, p<IOutputStream> writer) throw (IOException)
{
    int size = 0 ;

    size += marshaller->marshalInt(commandId, mode, writer) ;
    size += marshaller->marshalBoolean(responseRequired, mode, writer) ; 
    size += marshaller->marshalInt(result, mode, writer) ; 
    return size ;
}

void IntegerResponse::unmarshal(p<IMarshaller> marshaller, int mode, p<IInputStream> reader) throw (IOException)
{
    commandId = marshaller->unmarshalInt(mode, reader) ;
    responseRequired = marshaller->unmarshalBoolean(mode, reader) ; 
    result = (marshaller->unmarshalInt(mode, reader)) ; 
}
