/*
* Copyright 2006 The Apache Software Foundation or its licensors, as
* applicable.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include "activemq/command/XATransactionId.hpp"

using namespace apache::activemq::command;

/*
 *
 *  Marshalling code for Open Wire Format for XATransactionId
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
XATransactionId::XATransactionId()
{
    this->formatId = 0 ;
    this->globalTransactionId = NULL ;
    this->branchQualifier = NULL ;
}

XATransactionId::~XATransactionId()
{
}

unsigned char XATransactionId::getDataStructureType()
{
    return XATransactionId::TYPE ; 
}

        
int XATransactionId::getFormatId()
{
    return formatId ;
}

void XATransactionId::setFormatId(int formatId)
{
    this->formatId = formatId ;
}

        
array<char> XATransactionId::getGlobalTransactionId()
{
    return globalTransactionId ;
}

void XATransactionId::setGlobalTransactionId(array<char> globalTransactionId)
{
    this->globalTransactionId = globalTransactionId ;
}

        
array<char> XATransactionId::getBranchQualifier()
{
    return branchQualifier ;
}

void XATransactionId::setBranchQualifier(array<char> branchQualifier)
{
    this->branchQualifier = branchQualifier ;
}

int XATransactionId::marshal(p<IMarshaller> marshaller, int mode, p<IOutputStream> writer) throw (IOException)
{
    int size = 0 ;

    size += marshaller->marshalInt(formatId, mode, writer) ; 
    size += marshaller->marshalByteArray(globalTransactionId, mode, writer) ; 
    size += marshaller->marshalByteArray(branchQualifier, mode, writer) ; 
    return size ;
}

void XATransactionId::unmarshal(p<IMarshaller> marshaller, int mode, p<IInputStream> reader) throw (IOException)
{
    formatId = (marshaller->unmarshalInt(mode, reader)) ; 
    globalTransactionId = (marshaller->unmarshalByteArray(mode, reader)) ; 
    branchQualifier = (marshaller->unmarshalByteArray(mode, reader)) ; 
}
