# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

apiVersion: v2
name: activemq
description: Apache ActiveMQ - the most popular open source, multi-protocol, Java-based message broker
type: application
version: 6.3.0-SNAPSHOT
appVersion: 6.2.1
home: https://activemq.apache.org/
icon: https://activemq.apache.org/assets/img/activemq_logo_icon.png
sources:
  - https://github.com/apache/activemq
keywords:
  - activemq
  - messaging
  - jms
  - broker
  - amqp
  - mqtt
  - stomp
maintainers:
  - name: Apache ActiveMQ PMC
    email: dev@activemq.apache.org
