/*
 * Copyright 2006 The Apache Software Foundation or its licensors, as
 * applicable.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "marshal/ConnectionInfoMarshaller.hpp"

using namespace apache::activemq::client::marshal;

/*
 *  Marshalling code for Open Wire Format for ConnectionInfo
 *
 * NOTE!: This file is autogenerated - do not modify!
 *        if you need to make a change, please see the Groovy scripts in the
 *        activemq-core module
 */

ConnectionInfoMarshaller::ConnectionInfoMarshaller()
{
    // no-op
}

ConnectionInfoMarshaller::~ConnectionInfoMarshaller()
{
    // no-op
}



IDataStructure* ConnectionInfoMarshaller::createObject() 
{
    return new ConnectionInfo();
}

char ConnectionInfoMarshaller::getDataStructureType() 
{
    return ConnectionInfo.ID_ConnectionInfo;
}

    /* 
     * Un-marshal an object instance from the data input stream
     */ 
void ConnectionInfoMarshaller::unmarshal(ProtocolFormat& wireFormat, Object o, BinaryReader& dataIn, BooleanStream& bs) 
{
    base.unmarshal(wireFormat, o, dataIn, bs);

    ConnectionInfo& info = (ConnectionInfo&) o;
        info.setConnectionId((org.apache.activemq.command.ConnectionId) tightUnmarsalCachedObject(wireFormat, dataIn, bs));
        info.setClientId(tightUnmarshalString(dataIn, bs));
        info.setPassword(tightUnmarshalString(dataIn, bs));
        info.setUserName(tightUnmarshalString(dataIn, bs));

        if (bs.readBoolean()) {
            short size = dataIn.readShort();
            org.apache.activemq.command.BrokerId value[] = new org.apache.activemq.command.BrokerId[size];
            for( int i=0; i < size; i++ ) {
                value[i] = (org.apache.activemq.command.BrokerId) tightUnmarsalNestedObject(wireFormat,dataIn, bs);
            }
            info.setBrokerPath(value);
        }
        else {
            info.setBrokerPath(null);
        }

}


/*
 * Write the booleans that this object uses to a BooleanStream
 */
int ConnectionInfoMarshaller::marshal1(ProtocolFormat& wireFormat, Object& o, BooleanStream& bs) {
    ConnectionInfo& info = (ConnectionInfo&) o;

    int rc = base.marshal1(wireFormat, info, bs);
    rc += marshal1CachedObject(wireFormat, info.getConnectionId(), bs);
    rc += writeString(info.getClientId(), bs);
    rc += writeString(info.getPassword(), bs);
    rc += writeString(info.getUserName(), bs);
    rc += marshalObjectArray(wireFormat, info.getBrokerPath(), bs);

    return rc + 0;
}

/* 
 * Write a object instance to data output stream
 */
void ConnectionInfoMarshaller::marshal2(ProtocolFormat& wireFormat, Object& o, BinaryWriter& dataOut, BooleanStream& bs) {
    base.marshal2(wireFormat, o, dataOut, bs);

    ConnectionInfo& info = (ConnectionInfo&) o;
    marshal2CachedObject(wireFormat, info.getConnectionId(), dataOut, bs);
    writeString(info.getClientId(), dataOut, bs);
    writeString(info.getPassword(), dataOut, bs);
    writeString(info.getUserName(), dataOut, bs);
    marshalObjectArray(wireFormat, info.getBrokerPath(), dataOut, bs);

}
