//
// Marshalling code for Open Wire Format for JournalTransaction
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;

using OpenWire.Client;
using OpenWire.Client.Core;

namespace OpenWire.Client.Commands
{
    public class JournalTransaction : AbstractCommand
    {
    			public const byte ID_JournalTransaction = 54;
    			
        TransactionId transactionId;
        byte type;
        bool wasPrepared;



        // TODO generate Equals method
        // TODO generate GetHashCode method
        // TODO generate ToString method


        public override byte GetCommandType() {
            return ID_JournalTransaction;
        }


        // Properties

        public TransactionId TransactionId
        {
            get { return transactionId; }
            set { this.transactionId = value; }            
        }

        public byte Type
        {
            get { return type; }
            set { this.type = value; }            
        }

        public bool WasPrepared
        {
            get { return wasPrepared; }
            set { this.wasPrepared = value; }            
        }

    }
}
