//
// Marshalling code for Open Wire Format for JournalQueueAck
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;

using OpenWire.Client;
using OpenWire.Client.Core;

namespace OpenWire.Client.Commands
{
    public class JournalQueueAck : AbstractCommand
    {
    			public const byte ID_JournalQueueAck = 52;
    			
        ActiveMQDestination destination;
        MessageAck messageAck;



        // TODO generate Equals method
        // TODO generate GetHashCode method
        // TODO generate ToString method


        public override byte GetCommandType() {
            return ID_JournalQueueAck;
        }


        // Properties

        public ActiveMQDestination Destination
        {
            get { return destination; }
            set { this.destination = value; }            
        }

        public MessageAck MessageAck
        {
            get { return messageAck; }
            set { this.messageAck = value; }            
        }

    }
}
