//
// Marshalling code for Open Wire Format for RemoveSubscriptionInfo
//
//
// NOTE!: This file is autogenerated - do not modify!
//        if you need to make a change, please see the Groovy scripts in the
//        activemq-openwire module
//

using System;
using System.Collections;

using OpenWire.Client;
using OpenWire.Client.Core;

namespace OpenWire.Client.Commands
{
    public class RemoveSubscriptionInfo : BaseCommand
    {
    			public const byte ID_RemoveSubscriptionInfo = 0;
    			
        ConnectionId connectionId;
        string subcriptionName;
        string clientId;



        // TODO generate Equals method
        // TODO generate GetHashCode method
        // TODO generate ToString method


        public override byte GetCommandType() {
            return ID_RemoveSubscriptionInfo;
        }


        // Properties

        public ConnectionId ConnectionId
        {
            get { return connectionId; }
            set { this.connectionId = value; }            
        }

        public string SubcriptionName
        {
            get { return subcriptionName; }
            set { this.subcriptionName = value; }            
        }

        public string ClientId
        {
            get { return clientId; }
            set { this.clientId = value; }            
        }

    }
}
