/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "marshal/ConsumerControlMarshaller.hpp"

using namespace apache::activemq::client::marshal;

/*
 *  Marshalling code for Open Wire Format for ConsumerControl
 *
 * NOTE!: This file is autogenerated - do not modify!
 *        if you need to make a change, please see the Groovy scripts in the
 *        activemq-core module
 */

ConsumerControlMarshaller::ConsumerControlMarshaller()
{
    // no-op
}

ConsumerControlMarshaller::~ConsumerControlMarshaller()
{
    // no-op
}



IDataStructure* ConsumerControlMarshaller::createObject() 
{
    return new ConsumerControl();
}

char ConsumerControlMarshaller::getDataStructureType() 
{
    return ConsumerControl.ID_ConsumerControl;
}

    /* 
     * Un-marshal an object instance from the data input stream
     */ 
void ConsumerControlMarshaller::unmarshal(ProtocolFormat& wireFormat, Object o, BinaryReader& dataIn, BooleanStream& bs) 
{
    base.unmarshal(wireFormat, o, dataIn, bs);

    ConsumerControl& info = (ConsumerControl&) o;
        info.setClose(bs.readBoolean());
        info.setConsumerId((org.apache.activemq.command.ConsumerId) tightUnmarsalNestedObject(wireFormat, dataIn, bs));
        info.setPrefetch(dataIn.readInt());

}


/*
 * Write the booleans that this object uses to a BooleanStream
 */
int ConsumerControlMarshaller::marshal1(ProtocolFormat& wireFormat, Object& o, BooleanStream& bs) {
    ConsumerControl& info = (ConsumerControl&) o;

    int rc = base.marshal1(wireFormat, info, bs);
    bs.writeBoolean(info.isClose());
    rc += marshal1NestedObject(wireFormat, info.getConsumerId(), bs);
    
    return rc + 1;
}

/* 
 * Write a object instance to data output stream
 */
void ConsumerControlMarshaller::marshal2(ProtocolFormat& wireFormat, Object& o, BinaryWriter& dataOut, BooleanStream& bs) {
    base.marshal2(wireFormat, o, dataOut, bs);

    ConsumerControl& info = (ConsumerControl&) o;
    bs.readBoolean();
    marshal2NestedObject(wireFormat, info.getConsumerId(), dataOut, bs);
    DataStreamMarshaller.writeInt(info.getPrefetch(), dataOut);

}
