/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "marshal/DataResponseMarshaller.hpp"

using namespace apache::activemq::client::marshal;

/*
 *  Marshalling code for Open Wire Format for DataResponse
 *
 * NOTE!: This file is autogenerated - do not modify!
 *        if you need to make a change, please see the Groovy scripts in the
 *        activemq-core module
 */

DataResponseMarshaller::DataResponseMarshaller()
{
    // no-op
}

DataResponseMarshaller::~DataResponseMarshaller()
{
    // no-op
}



IDataStructure* DataResponseMarshaller::createObject() 
{
    return new DataResponse();
}

char DataResponseMarshaller::getDataStructureType() 
{
    return DataResponse.ID_DataResponse;
}

    /* 
     * Un-marshal an object instance from the data input stream
     */ 
void DataResponseMarshaller::unmarshal(ProtocolFormat& wireFormat, Object o, BinaryReader& dataIn, BooleanStream& bs) 
{
    base.unmarshal(wireFormat, o, dataIn, bs);

    DataResponse& info = (DataResponse&) o;
        info.setData((org.apache.activemq.command.DataStructure) tightUnmarsalNestedObject(wireFormat, dataIn, bs));

}


/*
 * Write the booleans that this object uses to a BooleanStream
 */
int DataResponseMarshaller::marshal1(ProtocolFormat& wireFormat, Object& o, BooleanStream& bs) {
    DataResponse& info = (DataResponse&) o;

    int rc = base.marshal1(wireFormat, info, bs);
    rc += marshal1NestedObject(wireFormat, info.getData(), bs);

    return rc + 0;
}

/* 
 * Write a object instance to data output stream
 */
void DataResponseMarshaller::marshal2(ProtocolFormat& wireFormat, Object& o, BinaryWriter& dataOut, BooleanStream& bs) {
    base.marshal2(wireFormat, o, dataOut, bs);

    DataResponse& info = (DataResponse&) o;
    marshal2NestedObject(wireFormat, info.getData(), dataOut, bs);

}
