/*
 * Copyright 2006 The Apache Software Foundation or its licensors, as
 * applicable.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "marshal/DiscoveryEventMarshaller.hpp"

using namespace apache::activemq::client::marshal;

/*
 *  Marshalling code for Open Wire Format for DiscoveryEvent
 *
 * NOTE!: This file is autogenerated - do not modify!
 *        if you need to make a change, please see the Groovy scripts in the
 *        activemq-core module
 */

DiscoveryEventMarshaller::DiscoveryEventMarshaller()
{
    // no-op
}

DiscoveryEventMarshaller::~DiscoveryEventMarshaller()
{
    // no-op
}



DataStructure* DiscoveryEventMarshaller::createObject() 
{
    return new DiscoveryEvent();
}

byte DiscoveryEventMarshaller::getDataStructureType() 
{
    return DiscoveryEvent.ID_DiscoveryEvent;
}

    /* 
     * Un-marshal an object instance from the data input stream
     */ 
void DiscoveryEventMarshaller::unmarshal(OpenWireFormat& wireFormat, Object o, BinaryReader& dataIn, BooleanStream& bs) 
{
    base.unmarshal(wireFormat, o, dataIn, bs);

    DiscoveryEvent& info = (DiscoveryEvent&) o;
        info.setServiceName(tightUnmarshalString(dataIn, bs));
        info.setBrokerName(tightUnmarshalString(dataIn, bs));

}


/*
 * Write the booleans that this object uses to a BooleanStream
 */
int DiscoveryEventMarshaller::marshal1(OpenWireFormat& wireFormat, Object& o, BooleanStream& bs) {
    DiscoveryEvent& info = (DiscoveryEvent&) o;

    int rc = base.marshal1(wireFormat, info, bs);
    rc += writeString(info.getServiceName(), bs);
    rc += writeString(info.getBrokerName(), bs);

    return rc + 0;
}

/* 
 * Write a object instance to data output stream
 */
void DiscoveryEventMarshaller::marshal2(OpenWireFormat& wireFormat, Object& o, BinaryWriter& dataOut, BooleanStream& bs) {
    base.marshal2(wireFormat, o, dataOut, bs);

    DiscoveryEvent& info = (DiscoveryEvent&) o;
    writeString(info.getServiceName(), dataOut, bs);
    writeString(info.getBrokerName(), dataOut, bs);

}
