/*
 * Copyright 2006 The Apache Software Foundation or its licensors, as
 * applicable.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include "marshal/RemoveInfoMarshaller.hpp"

using namespace apache::activemq::client::marshal;

/*
 *  Marshalling code for Open Wire Format for RemoveInfo
 *
 * NOTE!: This file is autogenerated - do not modify!
 *        if you need to make a change, please see the Groovy scripts in the
 *        activemq-core module
 */

RemoveInfoMarshaller::RemoveInfoMarshaller()
{
    // no-op
}

RemoveInfoMarshaller::~RemoveInfoMarshaller()
{
    // no-op
}



DataStructure* RemoveInfoMarshaller::createObject() 
{
    return new RemoveInfo();
}

byte RemoveInfoMarshaller::getDataStructureType() 
{
    return RemoveInfo.ID_RemoveInfo;
}

    /* 
     * Un-marshal an object instance from the data input stream
     */ 
void RemoveInfoMarshaller::unmarshal(OpenWireFormat& wireFormat, Object o, BinaryReader& dataIn, BooleanStream& bs) 
{
    base.unmarshal(wireFormat, o, dataIn, bs);

    RemoveInfo& info = (RemoveInfo&) o;
        info.setObjectId((org.apache.activemq.command.DataStructure) tightUnmarsalCachedObject(wireFormat, dataIn, bs));

}


/*
 * Write the booleans that this object uses to a BooleanStream
 */
int RemoveInfoMarshaller::marshal1(OpenWireFormat& wireFormat, Object& o, BooleanStream& bs) {
    RemoveInfo& info = (RemoveInfo&) o;

    int rc = base.marshal1(wireFormat, info, bs);
    rc += marshal1CachedObject(wireFormat, info.getObjectId(), bs);

    return rc + 0;
}

/* 
 * Write a object instance to data output stream
 */
void RemoveInfoMarshaller::marshal2(OpenWireFormat& wireFormat, Object& o, BinaryWriter& dataOut, BooleanStream& bs) {
    base.marshal2(wireFormat, o, dataOut, bs);

    RemoveInfo& info = (RemoveInfo&) o;
    marshal2CachedObject(wireFormat, info.getObjectId(), dataOut, bs);

}
