/*
* Copyright 2006 The Apache Software Foundation or its licensors, as
* applicable.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*/
#include "command/ProducerId.hpp"

using namespace apache::activemq::client::command;

/*
 *
 *  Marshalling code for Open Wire Format for ProducerId
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Groovy scripts in the
 *         activemq-core module
 *
 */
ProducerId::ProducerId()
{
    this->connectionId = 0 ;
    this->value = 0 ;
    this->sessionId = 0 ;
}

ProducerId::~ProducerId()
{
}

        
p<string> ProducerId::getConnectionId()
{
    return connectionId ;
}

void ProducerId::setConnectionId(p<string> connectionId)
{
    this->connectionId = connectionId ;
}

        
long long ProducerId::getValue()
{
    return value ;
}

void ProducerId::setValue(long long value)
{
    this->value = value ;
}

        
long long ProducerId::getSessionId()
{
    return sessionId ;
}

void ProducerId::setSessionId(long long sessionId)
{
    this->sessionId = sessionId ;
}
