jobs:
  runners:
    runs-on: ubuntu-latest
    outputs:
      list: ${{ steps.list.outputs.all }}
    steps:
      - id: list
        uses: snow-actions/list-github-hosted-runners@v1.0.0

  test:
    needs: [ runners ]
    strategy:
      fail-fast: false
      matrix:
        runner: ${{ fromJSON(needs.runners.outputs.list) }}
    runs-on: ${{ matrix.runner }}
